version: 2
stages:
  build:
    working_directory: /home/circleci/drun
    machine: true
    docker:
      - image: docker:17.03.0
    environment:
      RM_OPT: "" # tells drun not to --rm since CircleCI doesn't like it
    steps:
      - type: shell
        pwd: /
        shell: /bin/sh
        command: apk --update add git openssh checkbashisms
      - type: checkout
      - type: shell
        shell: /bin/sh
        command: checkbashisms -f ./drun
      - type: setup-docker-engine
      - type: shell
        shell: /bin/sh
        command: env
      - type: shell
        shell: /bin/sh
        command: |
          docker version
          docker --help
          docker info
          docker --log-level debug ps
          find /tmp/docker-*
          mkdir -p /home/circleci/drun/.docker/
          cp ${DOCKER_CERT_PATH}/*.pem /home/circleci/drun/.docker/
          ls -lha /home/circleci/drun/.docker/
          ./drun -x alpine:3.5 ls -lha /home/circleci/drun/
          ./drun -x alpine:3.5 ls -lha /home/circleci/drun/.docker/
      - type: shell
        shell: /bin/sh
        command: ./drun -x alpine:3.5 date
      - type: shell
        shell: /bin/sh
        command: ./drun -x alpine:3.5 cat /etc/issue | grep 'Alpine Linux 3.5' # should execute command inside container
      - type: shell
        shell: /bin/sh
        command: ./drun -x docker:17.03.0 docker version # should bind docker.sock
      - type: shell
        shell: /bin/sh
        command: ./drun -x docker:1.10.0 sh -c './drun -x docker:1.10.0 true' # should do inception in 2 levels
      - type: shell
        shell: /bin/sh
        command: ./drun -x docker:1.10.0 sh -c './drun -x docker:1.10.0 sh -c "./drun -x docker:1.10.0 true"' # should do inception in 3 levels
      - type: shell
        shell: /bin/sh
        command: ./drun -x mhart/alpine-node:5.12.0 node --version | grep 'v5.12.0' # should get version of node
      - type: shell
        shell: /bin/sh
        command: ./drun -xNA node --version | grep 'v7.7.1' # should read version from package.json with mhart/alpine-node-auto image
      - type: shell
        shell: /bin/sh
        command: ./drun -xNM slim node --version | grep 'v7.7.1' # should read version from package.json node:7.7.1-slim image
      - type: shell
        shell: /bin/sh
        command: echo '{"test":"passing"}' | ./drun -x stedolan/jq '.test' | grep '"passing"' # should pipe into command inside container
      - type: shell
        shell: /bin/sh
        command: echo '{"test":"passing"}' > test.json && ./drun -x stedolan/jq '.test' test.json | grep '"passing"' # should mount current directory
      - type: shell
        shell: /bin/sh
        command: ./drun -?
